### ISSUE TITLE
Massive audio play on ios lead to memory leaks.

### ISSUE THREAD

**Issue by yum650350** [luanpotter/flame#70] opened 2019-04-01 08:28 UTC
I'm making a game contains a sound effect that plays frequently. 
After playing for a while, first the sounds missing, and then app crash, ios crash.

The first method I use is
`Flame.audio.play('xxx.mp3');`
On Android it works perfectly, but ios will crash after playing a while. 

After some researching, according to [this](https://github.com/luanpotter/audioplayers/issues/56).
I try `AudioPool` as well, but another problem came.
It works perfectly on Android as it always does, but it can't play on IOS, not a single sound.

At last I made my own method, it works for me.
I do something like this.

```
Class MyAudio{
  static int playIndex=0;
  static List<AudioPlayer> playerList = [AudioPlayer(),AudioPlayer(),AudioPlayer()];
  static AudioPlayer get getPlayer{
    playIndex = playIndex < playerList.length - 1 ? playIndex + 1 : 0;
    return playerList[playIndex];
  }
  static init() async{
    playerList.forEach((au){
      au.setUrl((await Flame.audio.load('xxx.mp3')).path, isLocal: true);
      au.setVolumn(.8);
    });
  }
}

main() async{
  await MyAudio.init();
  ...
}
```
And play it by using
`MyAudio.getPlayer.resume();`

The first and the second method I have used, I'm wondering if I it's the version problem,
by the way my enviroment is:
```
$ flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (6 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```
and I use version `0.10.2` of Flame.

I tried upgrade Flutter to branch `master` to use `0.10.3 Flame`, but Flutter seems to become out of my control, errors occur, after I get rid of the errors, my `Flame.audio.play('xxx.mp3');` and `AudioPool` issue remain the same, I gave up and reinstall Flutter to user the `stable` branch.

This is all I been through, hope it can help someone.

**Comment by feroult** [comment] 2019-04-01 23:43
Hi @yum650350 thanks for reporting.

Just to make clear, does it work without crash using the `MyAudio` with 3 static players?

It could tell us that the problem is in `AudtioCache` but it does work on `Android`.

**Comment by yum650350** [comment] 2019-04-02 18:53
Yes, after I use `MyAudio`, no crash anymore.

**Comment by luanpotter** [comment] 2019-04-16 12:14
@feroult do we need to change anything over audioplayers? We can open this issue there, what do you think?

**Comment by feroult** [comment] 2019-04-16 12:29
Just opened the issue there: https://github.com/luanpotter/audioplayers/issues/141

**Comment by luanpotter** [comment] 2019-04-19 15:44
Closing in favour of luanpotter/audioplayers#141.

**Closed by luanpotter** 2019-04-19 15:44 UTC

**Comment by antrjec85** [comment] 2023-10-06 03:07
After I switched from FlameAudio.play("mp3") to AudioPool.createPool(), I was able to resolve the memory overflow issue on iOS, but I encountered a problem on Android
