### ISSUE TITLE
Why my sequenced animation works incorrectly?

### ISSUE THREAD

**Issue by spkingr** [luanpotter/flame#17] opened 2018-07-20 04:59 UTC
I use `AnimationComponent.sequenced` to make the animation sprite in my code, but it renders the whole images again and again(just flash in my screen), that is not what I wanted, the animation should be played with one frame and then another, here is the code:

```
this._createSwan().then((swan) => this.add(
        this.swan = swan
          ..x = this.viewport.size.width / 2
          ..y = this.viewport.size.height / 3
    ));

Future<AnimationComponent> _createSwan() async{
    await Flame.images.load("SwanSheet.png");
    final size = 64.0;
    return AnimationComponent.sequenced(size, size, "SwanSheet.png", 8, textureWidth: 2000.0, textureHeight: 250.0,);
  }
```

The image is 2000 pixels width and 250 height, with 8 swan-sprite made. How to use the animation components? Help and thanks very much!

**Comment by spkingr** [comment] 2018-07-20 07:01
Another question: 
* How to destroy or remove the component from the game world? I use `component.world.destroyBody(component.body);` , but it not works.
* Can `ContactListener` work with `KINEMATIC` boy type? And how to test the collision between `DYNAMIC` body with `KINEMATIC` body?

Thanks!

**Comment by feroult** [comment] 2018-07-20 14:49
@spkingr  Inside a `Box2DComponent` we have the `world` and `components` attribute. The first controls the mechanics and the later the rendering. You can check the top of the file:

```dart
  World world;
  List<BodyComponent> components = [];
```

I think the problem is that the `world.destroyBody` is not removing the component from the `components` list.

It is probably a better design to have an API to make the process of creating and destroying bodies atomically change this two variables.

**Comment by feroult** [comment] 2018-07-20 19:11
Just created an API: https://github.com/luanpotter/flame/commit/443f3049c71f1c6552f5b665e343f73cf6bfc36a

`Box2DComponent.remove(BodyComponent)`

**Comment by spkingr** [comment] 2018-07-21 01:08
@luanpotter  Thanks very much! I have tried and it works fine now. Is there any API like `flip` or `scaleX` to flip the animation sprites? The swan sprite is always backward with face forward.

**Comment by spkingr** [comment] 2018-07-21 01:37
@feroult 
I got it, thank you!
I edit the source code in my project, and I found some problems:

1. I cannot add any common `component` like `ParallaxComponent` and `AnimationComponent` anymore
2. I removed the body, however, it still situated in the world, and responses the physics
3. I found that `userData` defined in `BodyDef` or `Body` is useless. After reading the source code, I change the code in `fixture.dart`, this line:

```
void create(Body body, FixtureDef def) {
    userData = def.userData;
    //...
```
to
```
void create(Body body, FixtureDef def) {
    //userData = def.userData;
    userData = body.userData;
    //...
```
It works for me now in collision detection.

I try to change the code in `Box2DComponent` class:

```
void remove(BodyComponent component){
    components.remove(component);

    component.body.setActive(false); //added
    component.body.userData = null; //added
    world.destroyBody(component.body);
}

@override
  void render(canvas) {
    if (viewport.size == new Size(0.0, 0.0)) {
      return;
    }
    components.forEach((c) {
      if(c.body.isActive()){ //added
        c.render(canvas);
      }
    });
  }
```

But the problem 1 and 2 still there, help, thanks!

**Comment by feroult** [comment] 2018-07-21 01:44
I made this change to the API so the Box2D Component would only accept `BodyComponents` and no  regular components anymore.

You can still mix then in the higher-level Game `render` method.

I think this way we have a better design, what do you think?

**Comment by spkingr** [comment] 2018-07-23 06:18
That's okay, separate the physic components with regular ones will be much more efficiency. And I think sometimes the simple game won't need physic at all, supply some util methods for math is enough.
By the way, can we use `libgdx` in Flutter?

**Comment by luanpotter** [comment] 2018-08-06 01:30
@spkingr, AFAIK it's not possible to use libgdx with flutter; libgdx is a different framework that works with Java and also provide the ability to make multi-platform games, but their are not compatible. In flame we use Flutter low levels API to render, witch are similar to OpenGL bindings, but not exactly the same.

**Comment by spkingr** [comment] 2018-08-06 15:04
@luanpotter I got it. I have cloned `flame` library just now, I will try to make clear how the code works, try to have a look insight into it. I think make games in Flutter is great and challengeable. By the way, where should I get started to dive into? Thanks.  :)

**Comment by luanpotter** [comment] 2018-08-07 13:41
I'd suggest reading the `README.md` tutorial, it's the very basic needed for a very simple game (probably you've already done so and are more advanced). Then, you can read the complete guide for more in-depth explanations, the source code & docs have pretty good details too. Finally, take a look at our 'sample' games;

* [flame-example](https://github.com/luanpotter/flame-example): is VERY simple, comes with a tutorial, a bit outdated
* [bgug](https://github.com/luanpotter/bgug): a complete game, a bit outdated as well, but finished with most stuff a game could have (no box2d though)
* [haunt](https://github.com/feroult/haunt): an incomplete game featuring box2d and the most recent version of the APIs, has a few features but is not finished yet

You can also open issues with questions, help with PRs and please send us your work to eventually be showcased here (we are planning on something along those lines).

Thanks for your interest!

**Comment by luanpotter** [comment] 2018-08-12 13:51
@spkingr I will close this issue for now, if you have more questions or would like to submit issues, prs, et cetera, please feel free to open new issues!

**Closed by luanpotter** 2018-08-12 13:51 UTC
