### ISSUE TITLE
because flame >=0.10.0 depends on tiled ^0.2.0, flutter_driver from sdk is incompatible with flame >=0.10.0

### ISSUE THREAD

**Issue by olisteadman** [luanpotter/flame#40] opened 2019-02-14 08:57 UTC
Building my app 'nanny_mc', I see this error in CI/CD (using Codemagic):
```
== Install Flutter dependencies ==
Resolving dependencies...
Because every version of flutter_driver from sdk depends on convert 2.0.2 and every version of tiled depends on convert ^2.1.1, flutter_driver from sdk is incompatible with tiled.
And because flame >=0.10.0 depends on tiled ^0.2.0, flutter_driver from sdk is incompatible with flame >=0.10.0.
So, because nanny_mc depends on both flame 0.10.1 and flutter_driver any from sdk, version solving failed.
pub finished with exit code 1
```

In `pubspec.yaml`, if I replace `flame: 0.10.1` with `flame 0.10.0` the build still fails. Alternatively, if I remove flame entirely as follows,
<img width="822" alt="screen shot 2019-02-14 at 08 37 30" src="https://user-images.githubusercontent.com/12253176/52773880-dfefa280-3033-11e9-946c-4366de95f417.png">

... the build succeeds. 

Are you aware of this incompatibility between `flame` and `tiled`?

**Comment by erickzanardo** [comment] 2019-02-14 12:17
It seems that flutter_driver is depending on an older version of the convert package, tiled uses the newer one, `2.1.1` and by the looking of your error log, flutter_driver dependes on `2.0.2`.

I have looked about this flutter_driver package and it seems to be provided by the flutter sdk itself, are you using an updated version of flutter?

**Comment by olisteadman** [comment] 2019-02-14 18:06
```$ flutter --version
Flutter 1.1.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 985ccb6d14 (5 weeks ago) • 2019-01-08 13:45:55 -0800
Engine • revision 7112b72cc2
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
```

**Comment by Monotoba** [comment] 2019-02-19 20:17
Can't compile Flame on Android Studio 3.3.1

Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 28, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-45-generic

This error only occurs when Flame is added to the pubspec.yaml file of any project on my system. I've tried changing Flame version to no avail. I've tried using a hard coded version such as Flame: 0.10.1 with no effect. Removal of Flame from the pubspec.yaml file resolves the issue. However, it mean I can't build any projects that use flame. Which I really want to use! I would be very grateful for any help resolving this issue. Error info follow;

Compilation Error:

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "/home/randy/AndroidStudioProjects/barn_stormer_2/android/gradlew" exited abnormally:

> Configure project :audioplayers

[Fatal Error] asm-util-5.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] asm-5.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] asm-commons-5.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] proguard-gradle-5.3.3.pom:1:44: Content is not allowed in prolog.
[Fatal Error] asm-analysis-5.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] asm-tree-5.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] guava-22.0.pom:1:44: Content is not allowed in prolog.
[Fatal Error] httpmime-4.1.pom:1:44: Content is not allowed in prolog.
[Fatal Error] httpclient-4.2.6.pom:1:44: Content is not allowed in prolog.
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':audioplayers'.
> Could not resolve all artifacts for configuration ':audioplayers:classpath'.
   > Could not resolve org.ow2.asm:asm:5.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1
      > Could not resolve org.ow2.asm:asm:5.1.
         > Could not parse POM https://jcenter.bintray.com/org/ow2/asm/asm/5.1/asm-5.1.pom
            > Content is not allowed in prolog.
   > Could not resolve org.ow2.asm:asm-analysis:5.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1
      > Could not resolve org.ow2.asm:asm-analysis:5.1.
         > Could not parse POM https://jcenter.bintray.com/org/ow2/asm/asm-analysis/5.1/asm-analysis-5.1.pom
            > Content is not allowed in prolog.
   > Could not resolve org.ow2.asm:asm-commons:5.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1
      > Could not resolve org.ow2.asm:asm-commons:5.1.
         > Could not parse POM https://jcenter.bintray.com/org/ow2/asm/asm-commons/5.1/asm-commons-5.1.pom
            > Content is not allowed in prolog.
   > Could not resolve org.ow2.asm:asm-util:5.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1
      > Could not resolve org.ow2.asm:asm-util:5.1.
         > Could not parse POM https://jcenter.bintray.com/org/ow2/asm/asm-util/5.1/asm-util-5.1.pom
            > Content is not allowed in prolog.
   > Could not resolve net.sf.proguard:proguard-gradle:5.3.3.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1
      > Could not resolve net.sf.proguard:proguard-gradle:5.3.3.
         > Could not parse POM https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.3.3/proguard-gradle-5.3.3.pom
            > Content is not allowed in prolog.
   > Could not resolve org.ow2.asm:asm-tree:5.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1
      > Could not resolve org.ow2.asm:asm-tree:5.1.
         > Could not parse POM https://jcenter.bintray.com/org/ow2/asm/asm-tree/5.1/asm-tree-5.1.pom
            > Content is not allowed in prolog.
   > Could not resolve com.google.guava:guava:22.0.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:gradle-api:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.databinding:compilerCommon:3.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:common:26.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools.analytics-library:shared:26.0.1
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools.analytics-library:tracker:26.0.1
      > Could not resolve com.google.guava:guava:22.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.pom
            > Content is not allowed in prolog.
   > Could not resolve org.apache.httpcomponents:httpclient:4.2.6.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:sdklib:26.0.1
      > Could not resolve org.apache.httpcomponents:httpclient:4.2.6.
         > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.pom
            > Content is not allowed in prolog.
   > Could not resolve org.apache.httpcomponents:httpmime:4.1.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:sdklib:26.0.1
      > Could not resolve org.apache.httpcomponents:httpmime:4.1.
         > Could not parse POM https://jcenter.bintray.com/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.pom
            > Content is not allowed in prolog.
   > Could not resolve com.google.guava:guava:22.0.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.build:builder:3.0.1 > com.android.tools:sdklib:26.0.1 > com.android.tools:repository:26.0.1 > com.google.jimfs:jimfs:1.1
      > Could not resolve com.google.guava:guava:22.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.pom
            > Content is not allowed in prolog.
   > Could not resolve com.google.guava:guava:22.0.
     Required by:
         project :audioplayers > com.android.tools.build:gradle:3.0.1 > com.android.tools.build:gradle-core:3.0.1 > com.android.tools.lint:lint:26.0.1 > com.android.tools.lint:lint-checks:26.0.1 > com.android.tools.lint:lint-api:26.0.1 > com.android.tools.external.lombok:lombok-ast:0.2.3
      > Could not resolve com.google.guava:guava:22.0.
         > Could not parse POM https://jcenter.bintray.com/com/google/guava/guava/22.0/guava-22.0.pom
            > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /home/<user>/AndroidStudioProjects/barn_stormer_2/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by erickzanardo** [comment] 2019-02-20 02:10
@Monotoba this seems very odd, we will take a look into it, but this seems like a completely different problem from the error reported originally on this issue, could you please open a different issue? So we can target each problem individually?

Also, just fyi @olisteadman we are looking into this issue, and will report back as soon as we get to a solution

Thanks

**Comment by feroult** [comment] 2019-02-22 23:39
I couldn't reproduce your problem with `flutter_driver`.

But anyway I've downgraded the `convert` version of `tiled` to the same of `flame`.

Just waiting @luanpotter to release next version to check if it is working, please.

Regards

**Comment by erickzanardo** [comment] 2019-03-05 20:25
`0.10.2` is out for sometime now, have you tried on that version @olisteadman ?

**Comment by erickzanardo** [comment] 2019-03-15 13:09
Closing this due inactivity, if you still got problems with the new version, please let us know @olisteadman

**Closed by erickzanardo** 2019-03-15 13:09 UTC
